AWSTemplateFormatVersion: '2010-09-09'

Resources:

  GrafanaWorkspaceRole:
    Type: AWS::IAM::Role

    Properties:

      RoleName: grafana-workspace-role

      AssumeRolePolicyDocument:
        Version: '2012-10-17'

        Statement:
          - Effect: Allow

            Principal:
              Service:
                - grafana.amazonaws.com

            Action:
              - sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess

  PluginInstallerLambdaRole:
    Type: AWS::IAM::Role

    Properties:

      RoleName: grafana-plugin-installer-role

      AssumeRolePolicyDocument:
        Version: '2012-10-17'

        Statement:
          - Effect: Allow

            Principal:
              Service:
                - lambda.amazonaws.com

            Action:
              - sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      Policies:
        - PolicyName: grafana-plugin-policy

          PolicyDocument:
            Version: '2012-10-17'

            Statement:
              - Effect: Allow

                Action:
                  - grafana:DescribeWorkspace
                  - grafana:ListWorkspaces

                Resource: "*"
